<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf8" />
		<title></title>
		<link rel="stylesheet" href="public/css/style.css">
		
	</head>
	<body>
		<header>
			<div class="top">
				<div class="main">
					<ul>
						<li><Link to='/Info'> Thông tin tòa soạn </Link></li>
						<li><Link to='/Post'> Gửi bài cộng tác </Link></li>
						<li><Link to='/Media'> Media Kit </Link></li>
						<li><Link to='/Image'> Ảnh đẹp </Link></li>
						<li><Link to='/Video'> Video </Link></li>
						<li><Link to='/admin'> Admin </Link></li>
					</ul>
					<ul>
						<li><a href=""><i class="fa fa-facebook-square"></i></a></li>
						<li><a href=""><i class="fa fa-google-plus "></i></a></li>
						<li><a href=""><i class="fa fa-pinterest"></i></a></li>
						<li><input placeholder="Nhập từ khóa tìm kiếm" /></li>
					</ul>
				</div>
				
			</div>

			<div class="mid main">
				<Link to="/"><img src={logo} alt="" /> </Link>
			</div>
			

			<nav>
				<ul class="main">
					<li><a href=""> Tin tức </a>
						<ul>
							<li><a href="">Phóng sự </a></li>
							<li><a href="">Pháp luật </a></li>
						</ul>
					</li>
					<li><a href="tamsu"> Tâm sự </a></li>
					<li><a href=""> Gia đình  </a></li>
					<li><a href=""> Ngôi sao </a></li>
					<li><a href=""> Thời trang </a></li>
					<li><a href=""> Làm đẹp </a></li>
					<li><a href=""> Sức khỏe </a></li>
					<li><a href=""> Giáo dục </a></li>
					<li><a href=""> Phong thủy </a></li>
					<li><a href=""> Tử vi </a></li>
					<li><a href=""> Xu hướng </a></li>
				</ul>

			</nav>
			<div class="headding main">
				<ul>
					<li> <i class="myAnimation"></i> <a href="" > Tin tức 24h </a></li>
					<li> <a href="" > Tỉ giá ngoại tệ </a></li>
					<li> <a href="" > Giá vàng </a></li>
					<li> <a href="" > Dự báo thời tiết </a></li>
					<li> <a href="" > Tai nạn giao thông mới nhất </a></li>
				</ul>
			</div>
		</header>

		<div class="main">
			<div class="new_post">
				<div class="content_main">

					<div class="content">
						<div class="left">
							<img src={img1} />
							<h1><a href="">Giải cứu phi trường Tân Sơn Nhất, chông gai, nhọc nhằn, hy vọng... không của riêng ai!</a></h1>
							<p>Sau muôn nỗi nhọc nhằn chông gai, đợi chờ và hy vọng..., cuối cùng Thủ tướng Nguyễn Xuân Phúc cũng quyết định: Dừng mọi công trình hạ tầng phụ trợ sân golf Tân Sơn Nhất (khu biệt thự, khách sạn, nhà hàng...vv trong sân golf); để thuê tư vấn nước ngoài mở đường băng số 3 tiết kiệm hiệu quả, nhanh nhất.</p>
						</div>
						<div class="right">
							<a href=""> Cách dạy con bướng bỉnh “một phát nghe ngay” không cần quát mắng</a>
							<a href=""> Cách dạy con bướng bỉnh “một phát nghe ngay” không cần quát mắng</a>
							<a href=""> Cách dạy con bướng bỉnh “một phát nghe ngay” không cần quát mắng</a>
							<a href=""> Cách dạy con bướng bỉnh “một phát nghe ngay” không cần quát mắng</a>
							<a href=""> Cách dạy con bướng bỉnh “một phát nghe ngay” không cần quát mắng</a>
							<a href=""> Cách dạy con bướng bỉnh “một phát nghe ngay” không cần quát mắng</a>
						</div>
					</div>

					<div class="sidebar">

					</div>
				</div>
					
			</div>
			<div class="video">
				<div class="head">
					<h3><a href="">video</a></h3>
					<ul>
						<li><a href=""> Thời sự </a></li>
						<li><a href=""> Mẹo vặt </a></li>
						<li><a href=""> Fitness </a></li>
						<li><a href=""> Nội trợ </a></li>
						<li><a href=""> Review </a></li>
						<li><a href=""> Lạ & Hay </a></li>
						<li><a href=""> Funny </a></li>
						<li><a href=""> Sao </a></li>
						<li><a href=""> Làm đẹp </a></li>
						<li><a href=""> Mạng xã hội </a></li>
					</ul>
				</div>
				<div class="video_content">
					<div class="video_item">
						<a href=""><img src={img_v1} /></a>
						<a href="">"Sống chung với mẹ chồngđột ngột thay đổi kết thúc"</a>
					</div>
					<div class="video_item">
						<a href=""><img src={img_v1} /></a>
						<a href="">"Sống chung với mẹ chồng đột ngột thay đổi kết thúc"</a>
					</div>
					<div class="video_item">
						<a href=""><img src={img_v1} /></a>
						<a href="">"Sống chung với mẹ chồng đột ngột thay đổi kết thúc"</a>
					</div>
					<div class="video_item">
						<a href=""><img src={img_v1} /></a>
						<a href="">"Sống chung với mẹ chồng đột ngột thay đổi kết thúc"</a>
					</div>
					<div class="video_item">
						<a href=""><img src={img_v1} /></a>
						<a href="">"Sống chung với mẹ chồng đột ngột thay đổi kết thúc"</a>
					</div>
					<div class="video_item">
						<a href=""><img src={img_v1} /></a>
						<a href="">"Sống chung với mẹ chồng đột ngột thay đổi kết thúc"</a>
					</div>
				</div>
			</div>

			<div class="new_post news">
				<div class="head">
					<h3><a href="">Tin tức</a></h3>
					<ul>
						<li><a href=""> Phóng sự </a></li>
						<li><a href=""> Mẹo vặt </a></li>
						<li><a href=""> Pháp luật </a></li>
						<li><a href=""> Kinh doanh </a></li>
						<li><a href=""> Giao thông </a></li>
						<li><a href=""> Môi trường </a></li>
					</ul>
				</div>
				<div class="content_main">
					<div class="content">
						<div class="left">
							<div class="item">
								<a href=""><img src={img1} /></a>
								<a href="">Giải cứu phi trường Tân Sơn Nhất, chông gai, nhọc nhằn, hy vọng... không của riêng ai!</a>
								<p>Sau muôn nỗi nhọc nhằn chông gai, đợi chờ và hy vọng..., cuối cùng Thủ tướng Nguyễn Xuân Phúc cũng quyết định: Dừng mọi công trình hạ tầng phụ trợ sân golf Tân Sơn Nhất (khu biệt thự, khách sạn, nhà hàng...vv trong sân golf); để thuê tư vấn nước ngoài mở đường băng số 3 tiết kiệm hiệu quả, nhanh nhất.</p>
							</div>
							<div class="list">
								<div class="list_item">
									<a href="">​<img src={img2} /></a>
									<a href="">​Du khách Mỹ hết đường vào Triều Tiên</a>
								</div>

								<div class="list_item">
									<a href="">​<img src={img2} /></a>
									<a href="">​Du khách Mỹ hết đường vào Triều Tiên</a>
								</div>

								<div class="list_item">
									<a href="">​<img src={img2} /></a>
									<a href="">​Du khách Mỹ hết đường vào Triều Tiên</a>
								</div>
							</div>
						</div>
						<div class="right">
							<a href=""> Chủ tịch Hà Nội: “Không thể trồng xà cừ cổ thụ trên các tuyến phố”</a>
							<a href=""> Chủ tịch Hà Nội: “Không thể trồng xà cừ cổ thụ trên các tuyến phố”</a>
							<a href=""> Chủ tịch Hà Nội: “Không thể trồng xà cừ cổ thụ trên các tuyến phố”</a>
						</div>
					</div>
					<div class="sidebar">
					</div>
				</div>
					
			</div>
			
			<div class="star">
				<div class="content">
					<div class="head">
						<h3><a href="">Ngôi sao</a></h3>
						<ul>
							<li><a href=""> Showbiz </a></li>
							<li><a href=""> TV Show </a></li>
							<li><a href=""> Bài hát yêu thích </a></li>
							<li><a href=""> Phim hay </a></li>
						</ul>
					</div>

					<div class="content_main">
						<div class="content_head">
							<a href=""><img src={img3} /></a>

							<div class="right">
								<div class="right_item">
									<a href=""> Đồng nghiệp bức xúc bênh Phan Đinh Tùng sau scandal bắt nạt đàn em</a>
									<p>Nhạc sĩ Nguyễn Văn Chung, diễn viên Hữu Công… đã lên tiếng ngay sau khi ca sĩ Phan Đình Tùng bị nhiều người “ném đá” đi trễ show và tỏ thái độ coi thường đàn em gây xôn xao.</p>
								</div>
								<a href="">Hé lộ hóa đơn 7 tỷ Jennifer Lopez vung tay cho 2 ngày du hý với tình trẻ</a>
								<a href="">Terry trêu chọc chỗ nhạy cảm của Fabregas khi hôn bạn gái</a>
							</div>
						</div>
						<div class="content_bot">
							<div class="item">
								<a href=""><img src={img4} /></a>
								<a href="">Diễn viên trẻ bắn chết mẹ và em trai trước khi tự sát</a>
							</div>
							<div class="item">
								<a href=""><img src={img3} /></a>
								<a href="">Ngoại hình đẹp trai ngời ngời, cậu em của Miley Cyrus cũng đã chính thức "tấn công" showbiz!</a>
							</div>
							<div class="item">
								<a href=""><img src={img4} /></a>
								<a href="">Diễn viên trẻ bắn chết mẹ và em trai trước khi tự sát</a>
							</div>
						</div>
						
						<div class="section">
							<div class="item">
								<div class="head">
									<h3><a href="">Thời trang</a></h3>
								</div>
								<div class="item_top">
									<a href=""><img src={img5} /></a>
									<a href="">Hoàng Ku: Giám khảo "cool" nhất The Face, tiết lộ lý do từ chối làm việc cùng Hoàng Thùy lẫn Minh Tú</a>
								</div>
								<a href="">Dân mạng tưởng Trấn Thành mặc… nhầm quần của Hari Won đến dự sinh nhật Subeo vì bó “sít háng”</a>
								<a href="">The Face Việt Nam: "Nữ hoàng đi trễ" Minh Tú để thí sinh bơ vơ tự tập catwalk</a>
								<a href="">Xuất hiện áo lot hình viên đạn của chị em khiến mày râu thấp thỏm</a>
								<a href="">Choáng với cuộc sống sang chảnh tột cùng của công chúa Dubai</a>
								<a href="">Review giày ASICS RoadHawk FF - Sự kết hợp hoàn hảo giữa tốc độ và phong cách</a>

							</div>
							<div class="item">
								<div class="head">
									<h3><a href="">Làm đẹp</a></h3>
								</div>
								<div class="item_top">
									<a href=""><img src={img6} /></a>
									<a href="">Ra mắt Viện điều trị nám chuyên sâu đầu tiên tại Việt Nam</a>
								</div>
								<a href="">Lũ mụn ẩn “cứng đầu” đáng ghét cũng phải chào thua với cách chăm sóc siêu đơn giản này</a>
								<a href="">Ngày càng nhiều mẹ chọn làm đẹp vùng kín ngay khi đẻ xong, chuyên gia nói gì?</a>
								<a href="">Review thuốc nhuộm tóc 3CE Treatment Hair Tint đang hot nhất hiện nay</a>
								<a href="">8 phương pháp làm đẹp siêu lợi hại giúp phụ nữ châu Á “trẻ mãi không già”</a>
								<a href="">Chỉ với 1 quả trứng gà, chị em đã có vô vàn cách trị hết tàn nhang, da bật tông hiệu quả</a>
							</div>
						</div>

						<div class="section">
							<div class="item">
								<div class="head">
									<h3><a href="">Nấu ăn</a></h3>
								</div>
								<div class="item_top">
									<a href=""><img src={img5} /></a>
									<a href="">Hoàng Ku: Giám khảo "cool" nhất The Face, tiết lộ lý do từ chối làm việc cùng Hoàng Thùy lẫn Minh Tú</a>
								</div>
								<a href="">Dân mạng tưởng Trấn Thành mặc… nhầm quần của Hari Won đến dự sinh nhật Subeo vì bó “sít háng”</a>
								<a href="">The Face Việt Nam: "Nữ hoàng đi trễ" Minh Tú để thí sinh bơ vơ tự tập catwalk</a>
								<a href="">Xuất hiện áo lot hình viên đạn của chị em khiến mày râu thấp thỏm</a>
								<a href="">Choáng với cuộc sống sang chảnh tột cùng của công chúa Dubai</a>
								<a href="">Review giày ASICS RoadHawk FF - Sự kết hợp hoàn hảo giữa tốc độ và phong cách</a>

							</div>
							<div class="item">
								<div class="head">
									<h3><a href="">Sức khỏe</a></h3>
								</div>
								<div class="item_top">
									<a href=""><img src={img6} /></a>
									<a href="">Ra mắt Viện điều trị nám chuyên sâu đầu tiên tại Việt Nam</a>
								</div>
								<a href="">Lũ mụn ẩn “cứng đầu” đáng ghét cũng phải chào thua với cách chăm sóc siêu đơn giản này</a>
								<a href="">Ngày càng nhiều mẹ chọn làm đẹp vùng kín ngay khi đẻ xong, chuyên gia nói gì?</a>
								<a href="">Review thuốc nhuộm tóc 3CE Treatment Hair Tint đang hot nhất hiện nay</a>
								<a href="">8 phương pháp làm đẹp siêu lợi hại giúp phụ nữ châu Á “trẻ mãi không già”</a>
								<a href="">Chỉ với 1 quả trứng gà, chị em đã có vô vàn cách trị hết tàn nhang, da bật tông hiệu quả</a>
							</div>
						</div>

						<div class="section">
							<div class="item">
								<div class="head">
									<h3><a href="">Tử vi</a></h3>
								</div>
								<div class="item_top">
									<a href=""><img src={img5} /></a>
									<a href="">Hoàng Ku: Giám khảo "cool" nhất The Face, tiết lộ lý do từ chối làm việc cùng Hoàng Thùy lẫn Minh Tú</a>
								</div>
								<a href="">Dân mạng tưởng Trấn Thành mặc… nhầm quần của Hari Won đến dự sinh nhật Subeo vì bó “sít háng”</a>
								<a href="">The Face Việt Nam: "Nữ hoàng đi trễ" Minh Tú để thí sinh bơ vơ tự tập catwalk</a>
								<a href="">Xuất hiện áo lot hình viên đạn của chị em khiến mày râu thấp thỏm</a>
								<a href="">Choáng với cuộc sống sang chảnh tột cùng của công chúa Dubai</a>
								<a href="">Review giày ASICS RoadHawk FF - Sự kết hợp hoàn hảo giữa tốc độ và phong cách</a>

							</div>
							<div class="item">
								<div class="head">
									<h3><a href="">Phong thủy</a></h3>
								</div>
								<div class="item_top">
									<a href=""><img src={img6} /></a>
									<a href="">Ra mắt Viện điều trị nám chuyên sâu đầu tiên tại Việt Nam</a>
								</div>
								<a href="">Lũ mụn ẩn “cứng đầu” đáng ghét cũng phải chào thua với cách chăm sóc siêu đơn giản này</a>
								<a href="">Ngày càng nhiều mẹ chọn làm đẹp vùng kín ngay khi đẻ xong, chuyên gia nói gì?</a>
								<a href="">Review thuốc nhuộm tóc 3CE Treatment Hair Tint đang hot nhất hiện nay</a>
								<a href="">8 phương pháp làm đẹp siêu lợi hại giúp phụ nữ châu Á “trẻ mãi không già”</a>
								<a href="">Chỉ với 1 quả trứng gà, chị em đã có vô vàn cách trị hết tàn nhang, da bật tông hiệu quả</a>
							</div>
						</div>

						<div class="section">
							<div class="item">
								<div class="head">
									<h3><a href="">Gia đình</a></h3>
								</div>
								<div class="item_top">
									<a href=""><img src={img5} /></a>
									<a href="">Hoàng Ku: Giám khảo "cool" nhất The Face, tiết lộ lý do từ chối làm việc cùng Hoàng Thùy lẫn Minh Tú</a>
								</div>
								<a href="">Dân mạng tưởng Trấn Thành mặc… nhầm quần của Hari Won đến dự sinh nhật Subeo vì bó “sít háng”</a>
								<a href="">The Face Việt Nam: "Nữ hoàng đi trễ" Minh Tú để thí sinh bơ vơ tự tập catwalk</a>
								<a href="">Xuất hiện áo lot hình viên đạn của chị em khiến mày râu thấp thỏm</a>
								<a href="">Choáng với cuộc sống sang chảnh tột cùng của công chúa Dubai</a>
								<a href="">Review giày ASICS RoadHawk FF - Sự kết hợp hoàn hảo giữa tốc độ và phong cách</a>

							</div>
							<div class="item">
								<div class="head">
									<h3><a href="">Xu hướng</a></h3>
								</div>
								<div class="item_top">
									<a href=""><img src={img6} /></a>
									<a href="">Ra mắt Viện điều trị nám chuyên sâu đầu tiên tại Việt Nam</a>
								</div>
								<a href="">Lũ mụn ẩn “cứng đầu” đáng ghét cũng phải chào thua với cách chăm sóc siêu đơn giản này</a>
								<a href="">Ngày càng nhiều mẹ chọn làm đẹp vùng kín ngay khi đẻ xong, chuyên gia nói gì?</a>
								<a href="">Review thuốc nhuộm tóc 3CE Treatment Hair Tint đang hot nhất hiện nay</a>
								<a href="">8 phương pháp làm đẹp siêu lợi hại giúp phụ nữ châu Á “trẻ mãi không già”</a>
								<a href="">Chỉ với 1 quả trứng gà, chị em đã có vô vàn cách trị hết tàn nhang, da bật tông hiệu quả</a>
							</div>
						</div>
					</div>
				</div>
				<div class="sidebar">
				</div>
				
			</div>
		</div>

		<footer>
			<div class="sport main">
				<div class="sport_head">
					<a href=""> <i class="fa fa-life-ring" aria-hidden="true"></i> Đọc tin bóng đá </a>
				</div>
				<div class="head"> 
					<p> </p>
					<ul>
						<li> <a href=""> Nhan dinh bong da</a></li>
						<li> <a href=""> Truc tiep bong da</a></li>
						<li> <a href=""> Link sopcast</a></li>
						<li> <a href="">Livescore </a></li>
						<li> <a href="">Ket qua bong da truc tuyen </a></li>
						<li> <a href="">Video bong da </a></li>
					</ul>
				</div>
				<div class="video_content">
					<div class="video_item">
						<a href=""><img src={myLink.img} /></a>
						<a href="">Nhận định Nga vs Bồ Đào Nha</a>
					</div>
					<div class="video_item">
						<a href=""><img src={myLink.img} /></a>
						<a href="">Nhận định Nga vs Bồ Đào Nha</a>
					</div>
					<div class="video_item">
						<a href=""><img src={myLink.img} /></a>
						<a href="">Nhận định Nga vs Bồ Đào Nha</a>
					</div>
					<div class="video_item">
						<a href=""><img src={myLink.img} /></a>
						<a href="">Nhận định Nga vs Bồ Đào Nha</a>
					</div>
					<div class="video_item">
						<a href=""><img src={myLink.img} /></a>
						<a href="">Nhận định Nga vs Bồ Đào Nha</a>
					</div>
					<div class="video_item">
						<a href=""><img src={myLink.img} /></a>
						<a href="">Nhận định Nga vs Bồ Đào Nha</a>
					</div>
				</div>
			</div>

			<div class="footer">
				<div class="main">
					<div class="item">
						<p>© 2017 TamSuGiaDinh.vn</p>
						<p>Tam su gia dinh: nơi chia sẻ những tâm sự của phụ nữ về cuộc sống hạnh phúc gia đình hàng ngày, hôn nhân, tình yêu vợ chồng. Những tâm sự thầm kín, tâm sự những điều khó nói trong gia đình sẽ được các chuyên gia tâm lý của tamsugiadinh.vn tư vấn tận tình..</p>
						<p>Tại tamsugiadinh.vn bạn đọc có thể giãi bày những tâm sự buồn, chuyện phòng the, chuyện ngoại tình của vợ, chồng để được mọi người lắng nghe và chia sẻ.</p>
					</div>
					<div class="item">
						<p>Demo by Hoàng kun</p>
						<p>Địa chỉ: 377 Phạm Văn Đồng\, Từ Liêm\, Hà Nội</p>
						<p>VP: Vinsofts</p>

						<p>Liên hệ quảng cáo</p>
						<p>Hotline: 0978\.789\.177 (Mr Hoàng)</p>
						<p>Email: hoangsnow172@gmail.com</p>
					</div>
				</div>
			</div>
		</footer>
	</body>
</html>